version: "3"

services:
  poke-drip:
    build:
      context: .
    image: poke-drip-bot
    container_name: poke-drip-bot
    command: npm run serve
    volumes:
      - ./config:/poke-drip-bot/config
